### ISSUE TITLE
Invalid arguments issue

### ISSUE THREAD

**Issue by vaas-montenegro** [sweetgiorni/onedrive-file-picker#1]
Trying to upload a file using your script. here's the error I got
`{
  "error": {
    "code": "invalidRequest",
    "message": "One of the provided arguments is not acceptable.",
    "innerError": {
      "date": "2021-03-25T09:20:41",
      "request-id": "e10b6553-3452-4330-854b-c77ac704e227",
      "client-request-id": "e10b6553-3452-4330-854b-c77ac704e227"
    }
  }
}`

My code

`let config = {
                
clientId: "364c9ee5-f9c2-4c33-96fa-d300edc0f361",

                action: "save",

                sourceInputElementId: "fileUploadControl",

                sourceUri: dataUrl,

                fileName: "hello",

                openInNewWindow: true,

                advanced: {
                    redirectUri: "http://localhost:3002"
                },

                success: function (files) { console.log(files) },

                progress: function (percent) { console.log(percent) },

                cancel: function () { console.log('on cancel') },

                error: function (error) { console.log(error) }

            }

            window.OneDrive.save(config)`

**Comment by sweetgiorni** [comment]
This is a fork with a bug fix, I'm not maintaining it
